### PR TITLE
Use comma separated for assignees in issue template

### PR DESCRIPTION
**Pull request by pacospace**
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

### CODE REVIEW

**Review by tumido — COMMENTED** [review]
I don't think this is necessary. There should be a format in which the `assignees:` on line 5 should be applied. We may need to try formatting it to a coma separated list or something... Can you please see what would be the correct format?

**Comment by pacospace** [comment]
> I don't think this is necessary. There should be a format in which the `assignees:` on line 5 should be applied. We may need to try formatting it to a coma separated list or something... Can you please see what would be the correct format?

Thanks @tumido I had a look and it should be as you said, but there is an extra note.
```
assignees -> array of strings ( Logins for Users to assign to this issue. NOTE: Only users with push access can set assignees for new issues. Assignees are silently dropped otherwise. )
```
Ref: https://docs.github.com/en/rest/reference/issues#create-an-issue

**Comment by tumido** [comment]
@pacospace oh, ok. Can we use sesheta to auto-assign it to all of us then? Even for issues from users which don't have push access? Like via owners file or something...

**Comment by pacospace** [comment]
> @pacospace oh, ok. Can we use sesheta to auto-assign it to all of us then? Even for issues from users which don't have push access? Like via owners file or something...

cc @goern @harshad16

**Comment by harshad16** [comment]
Is the requirement here, for sesheta to assign all issue opened in this repo to specific peoples?
@pacospace @tumido

**Comment by pacospace** [comment]
> Is the requirement here, for sesheta to assign all issue opened in this repo to specific peoples?
> @pacospace @tumido

Not all issues of the repo, just the one used with a specific template for the specific workshop: https://github.com/operate-first/workshop-apps/blob/main/.github/ISSUE_TEMPLATE/ml_prague_workshop.md that contains the peoples assigned for that workshop.

**Review by tumido — APPROVED** [review]
/approve

**Pull request merged**
